# .streamlit/secrets.toml

# ==========================================
# 1. 数据库配置 (JSONBin.io)
# ==========================================
JSONBIN_BIN_ID = "69b35839c3097a1dd51e65ee"
JSONBIN_KEY = "$2a$10$lDOMrnOQuuGQztvWCBKXKeJuXvfCR6uIAl80N0J0RFdQoGPrfLUdS"

# ==========================================
# 2. 系统登录账号与权限配置
# ==========================================
[credentials.001]
password = "0311" # 这是管理员账号 admin 的密码，您可以自行修改
role = "001"     # 拥有覆写审计终端的最高权限

[credentials.002]
password = "123"   # 这是普通节点 user1 的密码，您可以自行修改
role = "002"      # 仅拥有 12小时内的有限修改权限
